import React, { useState, useEffect } from 'react'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import indexStyles from '../styles/pages/index.module.css'
import { Row, Col, List, Icon, Input, Upload, Button } from 'antd'
import { CalendarOutlined, FolderOutlined, FireOutlined, UploadOutlined } from '@ant-design/icons'
import Author from '../components/Author'
import Advert from '../components/Advert'
import Footer from '../components/Footer'
import { getList } from '../network/api'

export const getStaticProps = async () => {
  const { data } = await getList()
  return {
    props: {
      listDetail: data.data
    }
  }
}

export default function Home({ listDetail }) {
  const [mylist, setMylist] = useState(listDetail)
  const fileList = [
  ];
  const props = {
    name: 'file',
    action: 'http://localhost:7001/pic',
    headers: {
      authorization: 'authorization-text',
    },
    onChange(info) {
      if (info.file.status !== 'uploading') {
        console.log(info.file, info.fileList);
      }
      if (info.file.status === 'done') {
        message.success(`${info.file.name} file uploaded successfully`);
      } else if (info.file.status === 'error') {
        message.error(`${info.file.name} file upload failed.`);
      }
    },
  };

  

  return (
    <div >
      <Head>
        <title>Welcome Come To My Aloha Blog~~`</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Row className='comm_main' justify='center'>
        <Col className='comm_left' xs={24} sm={24} md={16} lg={18} xl={14}>
          <List
            header={<div style={{ marginLeft: 10 }}>全部消息</div>}
            itemLayout="vertical"
            dataSource={mylist}
            renderItem={item => (
              <List.Item>
                <div className={indexStyles.list_title}>
                  <Link href={{ pathname: '/detail', query: { id: item.id } }}>
                    <a >{item.title}</a>
                  </Link>
                </div>
                <div className={indexStyles.list_icon}>
                  <span><CalendarOutlined /> {item.addTime}</span>
                  <span><FolderOutlined /> {item.typeName}</span>
                  <span><FireOutlined /> {item.view_count}</span>
                </div>
                <div className={indexStyles.list_context}>{item.introduce}</div>
              </List.Item>
            )}
          />
        </Col>
        <Col className='comm_box' xs={0} sm={0} md={7} lg={5} xl={4}>
          <Author></Author>
          <Advert></Advert>
        </Col>
      </Row>
      <Footer></Footer>
      <div>
        <Upload
          action="http://localhost:7001/pic"
          listType="picture"
          defaultFileList={[...fileList]}
          data={[fileList[0]]}
        >
          <Button icon={<UploadOutlined />}>Upload</Button>
        </Upload>
        <img src='http://localhost:7001/getpic' alt='me' layout="fixed" width={100} height={100} />
      </div>
      <div>
        <Upload {...props}>
          <Button icon={<UploadOutlined />}>Click to Upload</Button>
        </Upload>
      </div>
    </div>
  )
}
